import { PGlite } from '../.local-work/tmp/knockout-sql-test/node_modules/@electric-sql/pglite/dist/index.js';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const db = new PGlite();
const admin='00000000-0000-4000-8000-000000000001', outsider='00000000-0000-4000-8000-000000000002';
const tid='10000000-0000-4000-8000-000000000001';
const ids=[1,2,3,4].map(i=>`20000000-0000-4000-8000-00000000000${i}`);
await db.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key); insert into auth.users values('${admin}'),('${outsider}'); create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$; grant usage on schema auth to authenticated,anon; create table public.equipos(id uuid primary key); insert into public.equipos values ${ids.map(id=>`('${id}')`).join(',')}; create table public.partidos(torneo_id uuid,categoria text); insert into public.partidos values('${tid}','2014'); grant select on public.partidos,public.equipos to authenticated,anon;`);
await db.exec((await readFile('supabase/migrations/20260930000100_eliminatorias.sql','utf8')).replace(/^\uFEFF/,''));
await db.exec(`insert into eliminatorias_admins values('${admin}');set role authenticated;select set_config('request.jwt.claim.sub','${outsider}',false);`);
const payload=(fase,a,b,g1,g2,extra={})=>({torneo_id:tid,categoria:'2014',fase,equipo_local_id:ids[a],equipo_visitante_id:ids[b],goles_local:g1,goles_visitante:g2,penales_local:null,penales_visitante:null,estado:'OFICIAL',...extra});
const save=async(p,version=null)=>(await db.query('select to_jsonb(s) as value from public.guardar_eliminatoria($1::jsonb,$2::timestamptz) s',[JSON.stringify(p),version])).rows[0].value;
await assert.rejects(save(payload('SF1',0,1,2,0)),/row-level security/);
await db.exec(`select set_config('request.jwt.claim.sub','${admin}',false);`);
await assert.rejects(save(payload('F',0,2,1,0)),/Oficializa ambas/);
await assert.rejects(save(payload('SF1',0,1,1,1)),/check constraint/);
const sf1=await save(payload('SF1',0,1,2,0));
const sf2=await save(payload('SF2',2,3,1,1,{penales_local:3,penales_visitante:4}));
await assert.rejects(save(payload('SF1',0,1,3,0)),/Otro administrador/);
await assert.rejects(save(payload('F',0,2,1,0)),/no corresponden/);
await save(payload('F',0,3,2,1));
await save(payload('TP',1,2,0,1));
await assert.rejects(save(payload('SF1',0,1,0,1),sf1.updated_at),/Primero retira/);
await db.exec('reset role;set role anon;');
const publicRows=await db.query('select fase,estado from eliminatorias_partidos');assert.equal(publicRows.rows.length,4);
await assert.rejects(db.exec('delete from eliminatorias_partidos'),/permission denied/);
assert.equal((await db.query('select * from partidos')).rows.length,1);
await db.close();
console.log('SQL OK: RLS, official ties, penalties, advancement, stale edits, downstream corrections and group isolation.');
